### ISSUE TITLE
blueutil in bluetooth.py hardcoded to /usr/local/bin

### ISSUE THREAD

**Issue by disaac** [bmunoz89/alfred-wf-bluetooth-manager#10]
Currently on version 2.0.0 the blueutil is hardcoded to [`/usr/local/bin/blueutil`](https://github.com/bmunoz89/alfred-wf-bluetooth-manager/blob/ed64b49c6f8a12c7633723ea1158d7960815f4e7/bluetooth.py#L33).

blueutil is directed to be installed with brew however my brew installation does not use the default /usr/local/bin install location. Since this is an option with brew the path should try and be obtained from the environment or by requesting it from `brew` with `$(brew --prefix)/bin/blueutil`. Though not sure how from within the python script to obtain the brew executable path so I just hardcoded my specific location in the script.

**Comment by bmunoz89** [comment]
@disaac I'll check how to implement that, thanks 😉

**Comment by bmunoz89** [comment]
@disaac It would be great if you can check the fix 😁
