### ISSUE TITLE
No such file or directory in bset

### ISSUE THREAD

**Issue by ryosuketc** [bmunoz89/alfred-wf-bluetooth-manager#12]
`bset` returns an error - No such file or directory.

![image](https://user-images.githubusercontent.com/43229670/114636424-f839d580-9d01-11eb-9a17-00735639268e.png)
macOS 11.2
Alfred 4.3.2

I did no customization on this - just downloaded and opened in Alfred.

I found this workflow quite interesting and would love to use. Thanks in advance.

**Comment by ryosuketc** [comment]
I fixed the issue. My `brew` (and `blueutil`) was outside of the hardcoded directory.
https://github.com/bmunoz89/alfred-wf-bluetooth-manager/blob/6cb979e67c0db18be55efd43c3c8e07129d1ff75/bluetooth.py#L33-L34

We could potentially use Workflow Variables to make them customizable (I just changed the script itself though).

**Comment by bmunoz89** [comment]
@ryosuketc that's a pretty good idea! I'll check how to implement that 😋

**Comment by ryosuketc** [comment]
I tried the new version and this is awesome! Thank you @bmunoz89 for making it happen :)

**Comment by bmunoz89** [comment]
I'm glad to help 😄
