### ISSUE TITLE
Disconnect does not work on macOS Monterey

### ISSUE THREAD

**Issue by roele** [bmunoz89/alfred-wf-bluetooth-manager#14]
Disconnecting on macOS Monterey always ends with the message `Something goes wrong`. This seems related to [#58](https://github.com/toy/blueutil/issues/58) and the fact that it takes several seconds until the device is disconnected.

**Comment by bmunoz89** [comment]
I haven't updated to macOS monterey yet, I hope to be releasing a compatible version this week 😬

**Comment by ProHaller** [comment]
Same problem here, looking forward to the update. ^^

**Comment by bmunoz89** [comment]
thanks to @roele, it's ready to update and I also took the opportunity to add a new feature to wait until the device is connected leveraging the idea of that fix 🦾

[Release #2.4.1](https://github.com/bmunoz89/alfred-wf-bluetooth-manager/releases/tag/2.4.1)
