### ISSUE TITLE
Explain what is bluetooth default device

### ISSUE THREAD

**Issue by PatrickF1** [bmunoz89/alfred-wf-bluetooth-manager#15]
Hi, thanks for making this great plugin. The readme describes functionality for default devices but doesn't explain what it means. I think I know what it means but am not sure. I think it'd greatly benefit users if you included an explanation of what default device means. Thanks!

**Comment by bmunoz89** [comment]
I'll try :)

**Comment by PatrickF1** [comment]
Nice thanks! Great explanation
