### ISSUE TITLE
Cannot Use

### ISSUE THREAD

**Issue by helloimvictorchor** [bmunoz89/alfred-wf-bluetooth-manager#18]
Hi,

I can't get it to work, I don't know which step I did wrong, but it worked before, I've updated to version 3.0.0, but when I type bm, it doesn't give any instructions, and I followed your instructions have updated pthyhon to phyton 2.
<img width="705" alt="CleanShot 2022-06-12 at 17 24 46@2x" src="https://user-images.githubusercontent.com/87065622/173227161-cb9c1ab1-ea47-4a23-a580-62dadd780b33.png">
<img width="979" alt="CleanShot 2022-06-12 at 17 38 15@2x" src="https://user-images.githubusercontent.com/87065622/173227183-6b72f7c5-ab22-437b-a56e-f6e9133f10a7.png">

**Comment by bmunoz89** [comment]
@victorchor2868 sorry for the delay, seems like I'm not receiving notifications from this repo 🤔. Have you tried this step? https://github.com/bmunoz89/alfred-wf-bluetooth-manager#python-2-and-macos-monterrey well if you don't want to do that you can simple download the previous version if you don't have monterey https://github.com/bmunoz89/alfred-wf-bluetooth-manager/releases/download/2.4.1/Bluetooth.manager.alfredworkflow

**Comment by helloimvictorchor** [comment]
I am already updated to monterey, and also followed the instruction you guided us to do, I have been screenshot the terminal, can you help me check it? thank yo
<img width="559" alt="CleanShot 2022-06-25 at 01 00 23@2x" src="https://user-images.githubusercontent.com/87065622/175608765-60d61e2c-dd55-432a-9cdc-94d6d9ba005c.png">

<img width="552" alt="CleanShot 2022-06-25 at 01 00 05@2x" src="https://user-images.githubusercontent.com/87065622/175608752-5d1b2b41-cdb1-4ff5-8651-f12276d161c5.png">
u

**Comment by bmunoz89** [comment]
@victorchor2868 sure, so what I can see is that you have a different homebrew path(HOMEBREW_PREFIX), so what I think it should work for you is this:
```bash
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "/usr/local/bin/python"
```

If that's correct I will fix the README cause prolly you are not the only one with a diff homebrew path. Let me know if that works.

To check if it works try this command which should print the version:
```bash
/usr/local/bin/python --version
```
And of course the workflow should work now... hopefully 🙏

**Comment by victorchor2868** [comment]
I have been copied your instruction to the terminal, this is what i get. thank yo
![Uploading CleanShot 2022-06-25 at 12.53.47@2x.png…]()
u

**Comment by helloimvictorchor** [comment]
have been copied your instruction to the terminal, this is what i get. thank yo
<img width="567" alt="CleanShot 2022-06-25 at 12 55 42@2x" src="https://user-images.githubusercontent.com/87065622/175758649-e11df021-ff8d-489a-a743-578e1addf829.png">
u

**Comment by bmunoz89** [comment]
your terminal is complaining cause you need more permissions to add the link, try using sudo:

```bash
sudo ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "/usr/local/bin/python"
```

**Comment by helloimvictorchor** [comment]
Successful!!! Thank for your help, thank you so much
<img width="704" alt="CleanShot 2022-06-26 at 00 11 02@2x" src="https://user-images.githubusercontent.com/87065622/175781853-81e23b9f-3263-413d-9d81-3b37fd3dcce5.png">
