### ISSUE TITLE
Need your help again

### ISSUE THREAD

**Issue by helloimvictorchor** [bmunoz89/alfred-wf-bluetooth-manager#19]
Hi,

Sorry, due to today I have reformatted my mac, causing your workflow on my mac couldn't work again, I have already installed the phyton 2 [,](https://github.com/bmunoz89/alfred-wf-bluetooth-manager#python-2-and-macos-monterrey) and also because the path is different, I have also followed your instructions and attempted to change it on the terminal, but this time unsuccessfully to get it to work. hope you can help. thank you
![CleanShot 2022-06-28 at 20 42 01@2x](https://user-images.githubusercontent.com/87065622/176181098-7ba4f94d-d933-4f56-bc59-dc96bef3664c.png)

**Comment by bmunoz89** [comment]
hey @victorchor2868, did you do this first?
```bash
brew install pyenv
pyenv install 2.7.18
```

**Comment by helloimvictorchor** [comment]
Yes, I did it

**Comment by helloimvictorchor** [comment]
<img width="567" alt="CleanShot 2022-06-29 at 15 01 06@2x" src="https://user-images.githubusercontent.com/87065622/176372537-ee9bd0a7-598e-456c-9619-79c74cb40e5d.png">

**Comment by helloimvictorchor** [comment]
Last time, you teach me to do this step, I have also followed your instruction this time, but this time is unsuccessful
<img width="565" alt="CleanShot 2022-06-29 at 15 02 38@2x" src="https://user-images.githubusercontent.com/87065622/176373512-6ba7f3ad-56f8-4c2f-a4e8-c3955a890091.png">

**Comment by bmunoz89** [comment]
ok, it seems like the directory `/usr/local/bin/` does not exists, so you should created it, try this:
```bash
mkdir -p /usr/local/bin/
```
If it throws a permission error try it with sudo:
```bash
sudo mkdir -p /usr/local/bin/
```
And after that you should be able to use the `ln` command:

```bash
ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "/usr/local/bin/python"
```
or using sudo if throws an error:
```bash
sudo ln -s "${HOME}/.pyenv/versions/2.7.18/bin/python2.7" "/usr/local/bin/python"
```

**Comment by helloimvictorchor** [comment]
Work again, thanks for your help
