### ISSUE TITLE
Type bcs but it said something went wrong

### ISSUE THREAD

**Issue by helloimvictorchor** [bmunoz89/alfred-wf-bluetooth-manager#20]
Could you help me fix the issue? or it didn't an issue? workflow is worked, but just this command has an issue. 
![CleanShot 2023-09-30 at 17 33 20@2x](https://github.com/bmunoz89/alfred-wf-bluetooth-manager/assets/87065622/82940839-5f1c-4b74-b529-407d9418d2b9)

**Comment by bmunoz89** [comment]
follow up in #21
