### ISSUE TITLE
bds uses wrong MAC address

### ISSUE THREAD

**Issue by Acidham** [bmunoz89/alfred-wf-bluetooth-manager#6]
## Issue
When I try to disconnect a BT service the wrong mac address is used. When I run the command on CLI with the correct MAC address the device will be properly disconnected

## Steps to reproduce
1. bds →  select device
2. Debug shows: 
```
Bluetooth manager[Script Filter] Passing output '{"name": "Trackpad", "mac_address": "8c-85-90-f2-38-d0"}' to Run Script
```
3. Bluetooth Manager writes in Debug console with MAC address selected in WF `8c-85-90-f2-38-d0`
```
09:43:08 workflow.py:2061 DEBUG    ---------- Bluetooth manager (1.0.1) ----------
09:43:08 disconnect_device.py:31 DEBUG    7c-04-d0-8b-f4-05
09:43:08 disconnect_device.py:22 DEBUG    /usr/local/bin/BluetoothConnector --disconnect 7c-04-d0-8b-f4-05 --notify
```

**Comment by Acidham** [comment]
Pull Request #8 should fix the issue

**Comment by bmunoz89** [comment]
@Acidham Seems like you are using the previous version, try to delete it and download the last one from here https://github.com/bmunoz89/alfred-wf-bluetooth-manager/releases/tag/2.0.0

**Comment by Acidham** [comment]
Ok in this case something is wrong with your download link ...or maybe I did something weird ;)

**Comment by bmunoz89** [comment]
I just tried the link in README.md https://github.com/bmunoz89/alfred-wf-bluetooth-manager/releases/latest/download/Bluetooth.manager.alfredworkflow and looks ok 🤔
