### ISSUE TITLE
Allow to Fork repo

### ISSUE THREAD

**Issue by Acidham** [bmunoz89/alfred-wf-bluetooth-manager#7]
Seems you did not add source files to the repo. Please add it to allow forking.

**Comment by bmunoz89** [comment]
I saw that you already forked it, everything okay?

**Comment by Acidham** [comment]
Yep seems your source files were not up-to-date therefore I unzipped .alfredworfklow file and made a pull request. You need to release once merged. 
Don't forget to remove commented old code in the two files.

**Comment by bmunoz89** [comment]
What link did you use to download it?

**Comment by Acidham** [comment]
I don't know cannot find in history. But with 2.0.0 it works. Anyhow would be great to add src files to the repo for the future

**Comment by bmunoz89** [comment]
what do you mean with source files? Like what kind of file? 🤔

**Comment by Acidham** [comment]
Usually, it would be good to add the source files to the repo to allow others to fix or change things and then create a pull request. Once you accepted the Pull Request you create a new .alfredworfklow file and release it. Because nobody who forked can edit the code and pull request the binary (.alfredworfklow). 

Example: https://github.com/Acidham/search-alfred-workflows
(you can ignore the .alfredworkflow, I left it there because I didn't release the wf during beta releases)

**Comment by bmunoz89** [comment]
But that isn't necessary, because you can make a symlink to your cloned repository, for example: `ln -s ~/Documents/Python/awf-bluetooth-manager /Users/BorisM/Dropbox/Alfred4/Alfred.alfredpreferences/workflows/user.workflow.65DADA69-2045-4580-AAA7-8218D57D9488`

Anyhow, I wasn't expected a PR so soon, that is not your fault, but I'll create a CONTRIBUTING.md guide soon with more details

Thanks @Acidham

**Comment by Acidham** [comment]
That's a risk for example when you store eg apikeys etc this will also be committed via info.plist which is not a good idea

**Comment by bmunoz89** [comment]
But having a .alfredworkflow file doesn't ensure it either

**Comment by bmunoz89** [comment]
Or if you mean with source files, the files that I delete from the version `1.0.1`, that was on purpose, because now I just use one file [bluetooth.py](https://github.com/bmunoz89/alfred-wf-bluetooth-manager/blob/master/bluetooth.py)

**Comment by Acidham** [comment]
Sure but here on how I am releasing/committing wfs:
1. Export Alfred Workflow into the local git repo
2. .gitingore contains *.alfredworkflow
3. Inflate (unzip script) into the source directory
4. Commit
5. Create release with binary

I am sure it's not the smartest workflow but it ensures that repo contains clean source files for forking and the Alfred binary.

**Comment by Acidham** [comment]
..but you are right the source is there :/

I am screwed with the first mistake by downloading older release. I was not aware of that you changed py files.
